
import Image from 'next/image'
import Head from 'next/head'
import {useState, useEffect} from "react";
import {BsSearch} from "react-icons/bs";
import Weather from '../components/Weather';
import Spinner from "../public/spinner.gif";
// import {data} from "autoprefixer";
// require('dotenv').config();

// const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);



  const fetchWeather = async (e) => {
          e.preventDefault()
      // setLoading(true)
          const axiosRequest = require('axios');
          try {
              const url = `https://api.openweathermap.org/geo/1.0/direct?q=${city}&&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
              const response = await axiosRequest.get(url);
              const url2 = `https://api.openweathermap.org/data/2.5/forecast/daily?lat=${response.data[0].lat}&lon=${response.data[0].lon}&units=metric&cnt=16&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
              const response2 = await axiosRequest.get(url2);
              // setWeather(response2.data[0])
              setWeather(response2)

              for (let i = 0; i <= 16; i++) {
                console.log(response2.data.list[i])
              }
              // for (let a = 0; a <= 16; a++) {
              //     console.log("Day: " + response2.data.list[a].temp.day + "/ " +
              //         "Night: " + response2.data.list[a].temp.night)
              // }
              // const descriptions = [];
              // for (let i = 0; i < 16; i++) {
              //     const desc = response2.data.data.list[i];
              //     console.log(i)
              // }

          } catch (error) {
              console.error(error)
          }

        }


  if (loading){
      return <Spinner/>
  } else {

  return (
      <div>
        <Head>
          <title>Weather Next App</title>
          <meta name={'description'} content={'Generated by create next app'}/>
          <link rel={'icon'} href={"/favicon.ico"}/>
        </Head>
          {/*Overlay*/}
          <div className={'fixed top-0 left-0 right-0 bottom-0 bg-[#6f6f6f] z-[0]'}/>
          {/*Bg Image*/}
          {/*<Image src='https://images.unsplash.com/photo-1508108712903-49b7ef9b1df8?auto=format&fit=crop&q=80&w=2069&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'*/}
          {/*       className={'object-cover z-[0]'}*/}
          {/*       alt='/'*/}
          {/*       // layout={'fill'}*/}
          {/*       style={{width: '100%', height: '100%', position: 'absolute'}}*/}
          {/*       width={500}*/}
          {/*       height={500}*/}
          {/*       priority={true}*/}

          {/*/>*/}
          {/*Search*/}
          <div className={'relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 pb-12 text-white z-10'}>
              <form onSubmit={fetchWeather} className={'flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'}>
                  <div>
                      <input
                          onChange={(e) => setCity(e.target.value)}
                             className={'bg-transparent border-none text-white focus:outline-none text-2xl'}
                             type="text"
                             placeholder="Search City"/>
                  </div>
                  <button onClick={fetchWeather}>
                      <BsSearch size={20}/>
                  </button>
              </form>
          </div>
          {/*Weather*/}
          {weather.data && <Weather data={weather} /> }
          {/*{city && <Weather cityd={city}/> }*/}
      </div>
  );
  }
}

// 23 Oct 20:43
// ---------
//
//
// import Image from 'next/image'
// import Head from 'next/head'
// import axios from 'axios'
// import {useState, useEffect} from "react";
// import {BsSearch} from "react-icons/bs";
// import Weather from '../components/Weather'
// import Spinner from "../public/spinner.gif";
// // require('dotenv').config();
//
// // const inter = Inter({ subsets: ['latin'] })
//
//
//
// export default function Home() {
//
//   const [city, setCity] = useState('')
//   const [weather, setWeather] = useState({});
//   const [loading, setLoading] = useState(false);
//
//
//   const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
//   const fetchWeather = (e) => {
//       e.preventDefault()
//       setLoading(true)
//       axios.get(url).then((response) => {
//       setWeather(response.data)
//       })
//       .catch(function (error) {
//         console.error(error);
//       });
//       setCity('')
//       setLoading(false);
//
//   }
//
//   if (loading){
//       return <Spinner/>
//   } else {
//
//   return (
//       <div>
//         <Head>
//           <title>Weather Next App</title>
//           <meta name={'description'} content={'Generated by create next app'}/>
//           <link rel={'icon'} href={"/favicon.ico"}/>
//         </Head>
//           {/*Overlay*/}
//           <div className={'fixed top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'}/>
//           {/*Bg Image*/}
//           <Image src='https://images.unsplash.com/photo-1508108712903-49b7ef9b1df8?auto=format&fit=crop&q=80&w=2069&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
//                  className={'object-cover'}
//                  alt='/'
//                  // layout={'fill'}
//                  style={{width: '100%', height: '100%', position: 'absolute'}}
//                  width={500}
//                  height={500}
//                  priority={true}
//
//           />
//           {/*Search*/}
//           <div className={'relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'}>
//               <form onSubmit={fetchWeather} className={'flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'}>
//                   <div>
//                       <input
//                           onChange={(e) => {setCity(e.target.value); console.log(e.target.value)}}
//                              className={'bg-transparent border-none text-white focus:outline-none text-2xl'}
//                              type="text"
//                              placeholder={'Şehir ara'}/>
//                   </div>
//                   <button onClick={fetchWeather}>
//                       <BsSearch size={20}/>
//                   </button>
//               </form>
//           </div>
//           {/*Weather*/}
//           {weather.main && <Weather data={weather} />  }
//       </div>
//   );
//   }
// }
//
